"""
Streamlit dashboard for the idle economy simulator.

This file is responsible only for the user interface:

- collecting simulation inputs
- running the model
- displaying stats
- displaying graphs
- displaying the event table

The actual simulation maths lives in model.py.
"""

import pandas as pd
import plotly.express as px
import streamlit as st

from model import SimulationConfig, simulateFixedCost


def buildSimulationConfig() -> tuple[SimulationConfig, bool]:
    """
    Build a SimulationConfig object from Streamlit sidebar inputs.

    Returns:
        A tuple containing:
        - the configured SimulationConfig object
        - whether graph y-axes should use log scale
    """

    # Sidebar title for all simulation controls.
    st.sidebar.header("Simulation Settings")

    # Starting amount of currency.
    startingBalance = st.sidebar.number_input(
        "Starting balance",
        min_value=0.0,
        value=0.0,
        step=1.0,
    )

    # Starting number of producers.
    startingProducers = st.sidebar.number_input(
        "Starting producers",
        min_value=0,
        value=1,
        step=1,
    )

    # Fixed cost of buying one producer.
    producerCost = st.sidebar.number_input(
        "Producer cost",
        min_value=0.01,
        value=10.0,
        step=1.0,
    )

    # Income generated by one producer each second.
    incomePerProducer = st.sidebar.number_input(
        "Income per producer / second",
        min_value=0.0,
        value=1.0,
        step=0.1,
    )

    # Total length of the simulation.
    simulationDuration = st.sidebar.number_input(
        "Simulation duration / seconds",
        min_value=0.0,
        value=60.0,
        step=10.0,
    )

    # Maximum number of events before stopping.
    # This prevents explosive fixed-cost growth from creating too much data.
    maxEvents = st.sidebar.number_input(
        "Max events",
        min_value=1,
        value=10_000,
        step=100,
    )

    # Whether the graphs should use logarithmic y-axes.
    useLogScale = st.sidebar.checkbox(
        "Use log scale for graphs",
        value=False,
    )

    # Convert sidebar values into the model configuration object.
    config = SimulationConfig(
        startingBalance=startingBalance,
        startingProducers=startingProducers,
        producerCost=producerCost,
        incomePerProducer=incomePerProducer,
        simulationDuration=simulationDuration,
        maxEvents=maxEvents,
    )

    return config, useLogScale


def displayFinalStats(finalRow: dict) -> None:
    """
    Display the final simulation values as Streamlit metric cards.

    Args:
        finalRow:
            The final row of the simulation output.
    """

    st.subheader("Final Stats")

    # Create four stat columns across the page.
    col1, col2, col3, col4 = st.columns(4)

    # Display the most important end-state values.
    col1.metric("Final balance", f"{finalRow['balance']:.2f}")
    col2.metric("Producers", f"{finalRow['producers']}")
    col3.metric("Income / sec", f"{finalRow['incomePerSecond']:.2f}")
    col4.metric("Total earned", f"{finalRow['totalEarned']:.2f}")


def displayLineChart(
    df: pd.DataFrame,
    xColumn: str,
    yColumn: str,
    title: str,
    useLogScale: bool,
) -> None:
    """
    Display one Plotly line chart in the Streamlit app.

    Args:
        df:
            DataFrame containing simulation rows.

        xColumn:
            Name of the column to use on the x-axis.

        yColumn:
            Name of the column to use on the y-axis.

        title:
            Chart title.

        useLogScale:
            Whether to use a logarithmic y-axis.
    """

    # Create the line chart.
    fig = px.line(
        df,
        x=xColumn,
        y=yColumn,
        title=title,
    )

    # Apply either linear or logarithmic y-axis scaling.
    yAxisType = "log" if useLogScale else "linear"
    fig.update_yaxes(type=yAxisType)

    # Display the chart at full page width.
    st.plotly_chart(fig, use_container_width=True)


def main() -> None:
    """
    Run the Streamlit idle economy dashboard.
    """

    # Configure the browser tab and page layout.
    st.set_page_config(
        page_title="Idle Economy Simulator",
        layout="wide",
    )

    st.title("Idle Economy Simulator")

    # Build the simulation configuration from sidebar inputs.
    config, useLogScale = buildSimulationConfig()

    # Run the simulation using the pure model function.
    rows = simulateFixedCost(config)

    # Convert simulation rows into a DataFrame for tables and graphs.
    df = pd.DataFrame(rows)

    # The final row contains the end-state summary.
    finalRow = rows[-1]

    # Display final headline stats.
    displayFinalStats(finalRow)

    st.subheader("Simulation Graphs")

    # Display core economy graphs.
    displayLineChart(
        df=df,
        xColumn="time",
        yColumn="producers",
        title="Producers Over Time",
        useLogScale=useLogScale,
    )

    displayLineChart(
        df=df,
        xColumn="time",
        yColumn="incomePerSecond",
        title="Income Per Second Over Time",
        useLogScale=useLogScale,
    )

    displayLineChart(
        df=df,
        xColumn="time",
        yColumn="balance",
        title="Balance Over Time",
        useLogScale=useLogScale,
    )

    st.subheader("Event Table")

    # Display the raw event data.
    st.dataframe(df, use_container_width=True)


if __name__ == "__main__":
    main()