from dataclasses import dataclass
from typing import Any


@dataclass
class SimulationConfig:
    """
    Stores all input values for the idle economy simulation.

    This version models the simplest possible idle economy:

    - One currency.
    - One producer type.
    - The producer has a fixed price.
    - Each producer gives a fixed amount of income per second.
    - The player automatically buys producers whenever affordable.
    """

    # Starting amount of currency the player has.
    startingBalance: float = 0.0

    # Number of producers owned at the start of the simulation.
    startingProducers: int = 1

    # Fixed cost to buy one producer.
    producerCost: float = 10.0

    # Income generated by one producer per second.
    incomePerProducer: float = 1.0

    # Total amount of simulated time, measured in seconds.
    simulationDuration: float = 60.0

    # Safety limit to stop fixed-cost growth from producing too many events.
    maxEvents: int = 100_000


def simulateFixedCost(config: SimulationConfig) -> list[dict[str, Any]]:
    """
    Simulate a fixed-cost one-producer idle economy.

    This uses event-based simulation instead of tick-based simulation.

    Tick-based simulation would do this:

        every small time step:
            add income
            check if the player can buy

    Event-based simulation does this instead:

        calculate exactly when the next purchase happens
        jump directly to that time
        buy the producer
        record the event

    This is much faster and cleaner for mathematical modelling.

    Args:
        config:
            A SimulationConfig object containing the starting values and rules.

    Returns:
        A list of dictionaries.
        Each dictionary represents an important simulation event.
    """

    # Validate input values before simulation starts.
    if config.startingProducers < 0:
        raise ValueError("startingProducers cannot be negative.")

    if config.producerCost <= 0:
        raise ValueError("producerCost must be greater than 0.")

    if config.incomePerProducer < 0:
        raise ValueError("incomePerProducer cannot be negative.")

    if config.simulationDuration < 0:
        raise ValueError("simulationDuration cannot be negative.")

    if config.maxEvents <= 0:
        raise ValueError("maxEvents must be greater than 0.")

    # Current simulation time.
    time = 0.0

    # Current player balance.
    balance = config.startingBalance

    # Current number of producers owned.
    producers = config.startingProducers

    # Total money earned from production during the simulation.
    # This does not include startingBalance.
    totalEarned = 0.0

    # Stores all recorded simulation events.
    rows: list[dict[str, Any]] = []

    def recordRow(eventName: str) -> None:
        """
        Record the current simulation state.

        Args:
            eventName:
                A label for what happened at this point in the simulation.
                Examples: "start", "buy", "end", "maxEventsReached".
        """

        incomePerSecond = producers * config.incomePerProducer

        rows.append({
            "time": time,
            "balance": balance,
            "producers": producers,
            "incomePerSecond": incomePerSecond,
            "totalEarned": totalEarned,
            "event": eventName,
        })

    # Record the initial state before anything happens.
    recordRow("start")

    # Count only active simulation events, not the starting row.
    eventCount = 0

    # Run until the requested simulation duration is reached.
    while time < config.simulationDuration:
        # Stop if the simulation generates too many events.
        # This matters because fixed-cost producers grow explosively.
        if eventCount >= config.maxEvents:
            recordRow("maxEventsReached")
            return rows

        # If the player can already afford a producer, buy immediately.
        # This handles cases where startingBalance is already high.
        if balance >= config.producerCost:
            balance -= config.producerCost
            producers += 1
            eventCount += 1

            recordRow("buy")
            continue

        # Calculate current income rate.
        incomePerSecond = producers * config.incomePerProducer

        # If income is zero, the player cannot earn more money.
        # Move directly to the end of the simulation.
        if incomePerSecond <= 0:
            time = config.simulationDuration
            recordRow("end")
            return rows

        # Work out how much simulated time remains.
        remainingTime = config.simulationDuration - time

        # Work out how long until the next producer can be bought.
        timeToNextPurchase = (config.producerCost - balance) / incomePerSecond

        # If the next purchase would happen after the simulation ends,
        # just advance to the end and record the final state.
        if timeToNextPurchase > remainingTime:
            earned = incomePerSecond * remainingTime

            balance += earned
            totalEarned += earned
            time = config.simulationDuration

            recordRow("end")
            return rows

        # Otherwise, jump directly to the next purchase time.
        earned = incomePerSecond * timeToNextPurchase

        balance += earned
        totalEarned += earned
        time += timeToNextPurchase

        # Buy the producer immediately at that time.
        balance -= config.producerCost
        producers += 1
        eventCount += 1

        recordRow("buy")

    # If the loop exits naturally, record the final state.
    recordRow("end")

    return rows